location             = "westus"
resource_group_name  = "rg-dev-basicfunction-01"
storage_account_name = "stdevbasicfunction01"
source_content       = "<h1>Hello Joe</h1>"
index_document       = "index.html"